name: Flujo de trabajo
on:
  workflow_dispatch:
  push:
    branches: [ arreglosCole ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew jar
      - name: mi UVUS
        run: echo "fergarfer1"
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Ejecutando pruebas
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: mi UVUS
        run: echo "fergarfer1"